# Naive Bayes model

Before starting this you need to know all the theoritical concepts of Naive Bayes and Bayes theorem to have a better knowledge about this probabilistic classification problem.

---->Use example_train1.csv


In [2]:
import numpy as np
import pandas as pd
import sklearn

#loading document file to have an intution on it
docs=pd.read_csv("example_train1.csv")
docs

Document      Class
0         Teclov is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

Here we can see in above dataset that first column is of sentences and second column is of classifiers, in this data 3 statements are of education class and 2 are of cinema class...

In [4]:
#converting class label to numerical form
docs["Class"]=docs.Class.map({'cinema':0,'education':1})
docs

Document  Class
0         Teclov is a great educational institution.      1
1            Educational greatness depends on ethics      1
2  A story of great ethics and educational greatness      1
3                           Sholey is a great cinema      0
4                   good movie depends on good story      0

In [15]:
numpy_array=docs.as_matrix()
x=numpy_array[:,0]
y=numpy_array[:,1]
y=y.astype(int)
print(x)
print(y)

['Teclov is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
[1 1 1 0 0]


C:\Users\Sanket\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


# Model creation

---> To create a text model we need to use count vertorizer, its function is to convert each word of the data into vector and count the number of occurences of the data so that we can apply naive bayes to it.

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

#creating an object of countvectorizer
vec=CountVectorizer()

In [17]:
vec.fit(x)
vec.vocabulary_

{'teclov': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

# Removing stop words

We can remove stop words  like is,and,or, etc because these are of no use in the classification.

In [22]:
vec=CountVectorizer(stop_words="english")
vec.fit(x)
vec.vocabulary_

{'teclov': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [23]:
#printing feature names
print(vec.get_feature_names())
print(len(vec.get_feature_names()))

['cinema', 'depends', 'educational', 'ethics', 'good', 'great', 'greatness', 'institution', 'movie', 'sholey', 'story', 'teclov']
12


In [25]:
#another way of representing feature names 
x_transform=vec.transform(x)
print(x_transform)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [26]:
x=x_transform.toarray()
x

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [27]:
#converting matrix to dataframe
pd.DataFrame(x,columns=vec.get_feature_names())

cinema  depends  educational  ethics  good  great  greatness  institution  \
0       0        0            1       0     0      1          0            1   
1       0        1            1       1     0      0          1            0   
2       0        0            1       1     0      1          1            0   
3       1        0            0       0     0      1          0            0   
4       0        1            0       0     2      0          0            0   

   movie  sholey  story  teclov  
0      0       0      0       1  
1      0       0      0       0  
2      0       0      1       0  
3      0       1      0       0  
4      1       0      1       0

In [39]:
#now obtaining test data
test_docs=pd.read_csv("example_test1.csv")
test_docs

Document      Class
0  very good educational institution  education

In [40]:
test_docs['Class']=test_docs.Class.map({'cinema':0,'education':1})
test_docs['Class']=1
test_docs

Document  Class
0  very good educational institution      1

In [41]:
test_numpy_array=test_docs.as_matrix()
x_test=test_numpy_array[:,0]
y_test=test_numpy_array[:,1]
print(x_test)
print(y_test)

['very good educational institution']
[1]


C:\Users\Sanket\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [42]:
x_test_transformed=vec.transform(x_test)
x_test=x_test_transformed.toarray()
x_test

array([[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

# Multinomial Naive Bayes

In [43]:
#building a multinomial naive bayes model
from sklearn.naive_bayes import MultinomialNB

#creating object
mnb=MultinomialNB()

mnb.fit(x,y)

#predicting probability on test data
mnb.predict_proba(x_test) #this returns probability based on your classes

array([[0.32808399, 0.67191601]])

We created a model using multinomial naive bayes which is used for multiclass classification for any number of features.

-->This probability prediction shows 0.32.. for movies class and 0.67... for education class so definately this test data will fall under educaton class.


In [44]:
pd.DataFrame(mnb.predict_proba(x_test),columns=['cinema','education'])

cinema  education
0  0.328084   0.671916

# Bernoulli Naive Bayes

In [49]:
from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB()
bnb.fit(x,y)
bnb_pred=bnb.predict_proba(x_test)
pd.DataFrame(bnb_pred,columns=['cinema','education'])

cinema  education
0  0.232637   0.767363

We can observe that in this case bernoulli is creating a better model than multinomial..